//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatrohrmsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeQualificationDetail
    {
        public int intQualificationID { get; set; }
        public Nullable<int> intEmployeeID { get; set; }
        public string varQualificationLevel { get; set; }
        public string varUniversityName { get; set; }
        public string varSpecialization { get; set; }
        public Nullable<System.DateTime> dtStartYear { get; set; }
        public Nullable<System.DateTime> dtEndYear { get; set; }
        public string varPercentage { get; set; }
        public Nullable<int> intCreatedBy { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<int> intUpdatedBy { get; set; }
        public Nullable<System.DateTime> dyUpdatedOn { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
