//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatrohrmsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeGoal
    {
        public int intGoalID { get; set; }
        public string varTitle { get; set; }
        public string varGoalDescription { get; set; }
        public Nullable<System.DateTime> dtStartdate { get; set; }
        public Nullable<System.DateTime> dtEndDate { get; set; }
        public string varStatus { get; set; }
        public string varCompletion { get; set; }
        public string varManagerComment { get; set; }
        public Nullable<int> intEmployeeID { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<int> intUpdatedby { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
