//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatrohrmsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLinkDetail
    {
        public int iID { get; set; }
        public string sProjectStatus { get; set; }
        public string sTechnicalSkill { get; set; }
        public string sMeetGoals { get; set; }
        public string sAttention { get; set; }
        public string sPerformance { get; set; }
        public string sImproveComment { get; set; }
        public string sAdditionalComment { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<bool> bIsActive { get; set; }
        public Nullable<int> objClientID { get; set; }
        public Nullable<int> objEmployeeDetail { get; set; }
        public Nullable<int> objProjectDetail { get; set; }
    }
}
