//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatrohrmsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectDetail
    {
        public tblProjectDetail()
        {
            this.tblTimeSheets = new HashSet<tblTimeSheet>();
        }
    
        public int intProjectID { get; set; }
        public string varProjectName { get; set; }
        public Nullable<int> intInternalProjectHead { get; set; }
        public string varProjectDescription { get; set; }
        public Nullable<System.DateTime> dtProjectStartDate { get; set; }
        public Nullable<System.DateTime> dtProjectEndDate { get; set; }
        public Nullable<int> intProjectStatus { get; set; }
        public string varCompletion { get; set; }
        public Nullable<int> intClientID { get; set; }
        public string varClientProjectHead { get; set; }
        public string varTeamMemDetails { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<int> intUpdatedby { get; set; }
    
        public virtual tblClientDetail tblClientDetail { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblStatu tblStatu { get; set; }
        public virtual ICollection<tblTimeSheet> tblTimeSheets { get; set; }
    }
}
