//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatrohrmsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecruitment
    {
        public int intRecruitmentID { get; set; }
        public string varFirstName { get; set; }
        public string varMiddleName { get; set; }
        public string varLastName { get; set; }
        public string varEmailID { get; set; }
        public string varMobileNum { get; set; }
        public Nullable<int> intPositionID { get; set; }
        public string varResume { get; set; }
        public Nullable<System.DateTime> dtApplicationDate { get; set; }
        public Nullable<int> varComment { get; set; }
        public Nullable<System.DateTime> varStatus { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<int> intUpdatedby { get; set; }
    
        public virtual tblPosition tblPosition { get; set; }
    }
}
