//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatrohrmsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeSheet
    {
        public int intTimesheetId { get; set; }
        public Nullable<int> intClientID { get; set; }
        public Nullable<int> intProjectID { get; set; }
        public Nullable<int> intActivityID { get; set; }
        public string varActivityDescription { get; set; }
        public Nullable<int> varTimeSlot { get; set; }
        public Nullable<System.DateTime> dtTimesheetDate { get; set; }
        public Nullable<int> intEmployeeID { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<int> intUpdatedby { get; set; }
    
        public virtual tblActivityDetail tblActivityDetail { get; set; }
        public virtual tblClientDetail tblClientDetail { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblProjectDetail tblProjectDetail { get; set; }
    }
}
