//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatrohrmsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTraining
    {
        public int intTrainingID { get; set; }
        public string varTrainigsName { get; set; }
        public Nullable<int> intTrainerID { get; set; }
        public Nullable<System.DateTime> varTrainingStartDate { get; set; }
        public Nullable<System.DateTime> varTrainingEndDate { get; set; }
        public string varTrainingDetails { get; set; }
        public string varStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<int> intCreatedBy { get; set; }
        public Nullable<int> intUpdatedBy { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
