//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatrohrmsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLeaveManagement
    {
        public int intLeaveMgtID { get; set; }
        public Nullable<int> intEmployeeID { get; set; }
        public Nullable<System.DateTime> dtLeaveStartDate { get; set; }
        public Nullable<System.DateTime> dtLeaveEndDate { get; set; }
        public string varLeaveDescription { get; set; }
        public Nullable<int> intLeaveTypeId { get; set; }
        public string varStatus { get; set; }
        public string varManagerComment { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<int> intUpdatedby { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblLeaveType tblLeaveType { get; set; }
    }
}
