//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquatrohrmsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVacancise
    {
        public int intVacanciseID { get; set; }
        public Nullable<int> intPositionID { get; set; }
        public string varExperience { get; set; }
        public string varJobLocation { get; set; }
        public Nullable<int> intNoOfPositions { get; set; }
        public string varJobDescription { get; set; }
        public string varPublisher { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtUpdatedOn { get; set; }
        public Nullable<int> intCreatedby { get; set; }
        public Nullable<int> intUpdatedby { get; set; }
    
        public virtual tblPosition tblPosition { get; set; }
    }
}
